### ISSUE TITLE
add README with documentation

### ISSUE THREAD

**Issue by patraanjan23** [patraanjan23/covid19api#1]
Just add some documentation in a README.md file.

**Comment by Hinal-Srivastava** [comment]
Documentations related to?

**Comment by patraanjan23** [comment]
How to deploy and description of the API endpoints.

**Comment by ameykhale** [comment]
Have just created a pull request, please review

**Comment by Cheemashyper** [comment]
Okay, do you prefer Dark Mode or Light Mode?

**Comment by Cheemashyper** [comment]
Hello @patraanjan23 
Can you explain to me what the code does in brief?

**Comment by patraanjan23** [comment]
> Hello @patraanjan23
> Can you explain to me what the code does in brief?

Unfortunately this issue has already been assigned. Feel free to go through my other projects.
